---
title: "Project"
author: "Fiona Zhang"
date: "2024-02-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
input=read.table("Data2share.txt",sep="\t",header=T)

input <- input |>
  mutate(ever_symp = across(starts_with("symptom")) %>% rowSums > 0,
         ever_pos = across(starts_with("compar")) %>% rowSums(., na.rm = TRUE) > 0)
```

```{r}
long_df <- input |>
  select(-eligible) |>
  pivot_longer(
    cols = -newid, 
    names_to = c(".value", "day"), 
    names_pattern = "(.*)\\.(.*)"
  ) |>
  mutate(day = as.numeric(day))
```

```{r}
set.seed(1)
samp <- long_df |>
  distinct(newid) |>
  slice_sample(n = 1000)
long_df |>
  inner_join(samp, by = "newid") |>
  inner_join(input |> select(newid, ever_symp, ever_pos), by = "newid") |>
ggplot(aes(x = day, y = antigen_result, group = newid, color = ever_symp)) +
  geom_line(alpha = 0.5) +
  facet_wrap(~ever_symp)

long_df |>
  inner_join(input |> select(newid, ever_symp, ever_pos), by = "newid") |>
  filter(ever_pos) |>
  group_by(day, ever_symp) |>
  summarise(m = mean(antigen_result, na.rm = TRUE)) |>
ggplot(aes(x = day, y = m, color = ever_symp)) +
  geom_line() +
  facet_wrap(~ever_symp)
```

```{r}
long_df |>
  group_by(newid)
```
```{r}
set.seed(1)
samp <- long_df |>
  distinct(newid) |>
  slice_sample(n = 1000)
true_data <- long_df %>%
  inner_join(samp, by = "newid") |>
  inner_join(input |> select(newid, ever_symp, ever_pos), by = "newid") %>%
  filter(ever_symp == TRUE)

model_true <- lm(antigen_result ~ splines::ns(day, 4), data = true_data) 

true_data |>
  drop_na(antigen_result, day) |>
  mutate(yhat = fitted(model_true)) |>
  ggplot(aes(x = day, y = yhat)) + 
  geom_point() + 
  geom_line()

true_data |>
  filter(ever_pos) |>
  group_by(day) |>
  summarise(m = mean(antigen_result, na.rm = TRUE)) |>

  ggplot(aes(x = day, y = m)) +
  geom_line() 
ggplot(true_data, aes(x = day, y = antigen_result)) + 
  geom_point() +
  stat_smooth(method = "lm")

false_data <- long_df %>%
  inner_join(samp, by = "newid") |>
  inner_join(input |> select(newid, ever_symp, ever_pos), by = "newid") %>%
  filter(ever_symp == FALSE)
model_false <- lm(antigen_result ~ day, data = false_data)


model_false <- lm(antigen_result ~ splines::ns(day, 4), data = false_data) 

false_data |>
  drop_na(antigen_result, day) |>
  mutate(yhat = fitted(model_false)) |>
  ggplot(aes(x = day, y = yhat)) + 
  geom_point() + 
  geom_line()
ggplot(false_data, aes(x = day, y = antigen_result)) + 
  geom_point() +
  stat_smooth(method = "lm")
```

```{r}
true_data <- true_data|>
  mutate(antigenyes = lag(antigen_result)) |>
  mutate(antigenbye = lag(antigenyes))
model_yes <- lm(antigenyes ~ splines::ns(day + antigen_result, 4), data = true_data)
true_data <- true_data|>
  drop_na(antigenyes) |>
  mutate(antigenyes_hat = fitted(model_yes))
model_bye <- lm(antigenbye ~ splines::ns(day + antigenyes_hat, 4), data = true_data)
true_data <- true_data|>
  drop_na(antigenbye) |>
  mutate(antigenbye_hat = fitted(model_bye))
model_day <- lm(day ~ splines::ns(antigen_result + antigenyes_hat + antigenbye_hat, 4), data = true_data)
true_data <- true_data |>
  mutate(dayhat = fitted(model_day))
ggplot(true_data, aes(x = dayhat, y = antigen_result + antigenyes_hat + antigenbye_hat)) + 
  geom_point() +
  geom_line()
```

